
name: Node CI
on: push
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - run: make install
      - run: make lint 